#!/bin/bash
##########################################################
##                                                      ##
## GitHub:  https://github.com/QuickBox/QuickBox        ##
##                                                      ##
## Author:  ExtremeSTR - https://github.com/ExtremeSTR/ ##
##                                                      ##
## Email :  ExtremeSTRAUSSER@gmail.com                  ##
##                                                      ##
##########################################################
sleep 4
#Script Console Colors
black=$(tput setaf 0);
red=$(tput setaf 1); 
green=$(tput setaf 2); 
yellow=$(tput setaf 3);
blue=$(tput setaf 4); 
magenta=$(tput setaf 5); 
cyan=$(tput setaf 6); 
white=$(tput setaf 7);
on_red=$(tput setab 1); 
on_green=$(tput setab 2); 
on_yellow=$(tput setab 3); 
on_blue=$(tput setab 4);
on_magenta=$(tput setab 5); 
on_cyan=$(tput setab 6); 
on_white=$(tput setab 7); 
bold=$(tput bold);
dim=$(tput dim); 
underline=$(tput smul); 
reset_underline=$(tput rmul); 
standout=$(tput smso);
reset_standout=$(tput rmso); 
normal=$(tput sgr0); 
alert=${white}${on_red}; 
title=${standout};
sub_title=${bold}${yellow}; 
repo_title=${black}${on_green}; 
message_title=${white}${on_magenta}

## Dedecting...  ##
  if [[ $EUID != 0 ]]; then
    echo ${red}'This script must be run with root privileges.'${normal}
    echo 'Exiting...'
    exit 1
  fi
  echo "${blue}You're running as root. Let's continue...${normal} "
  echo
## İnstalling... ##
sudo apt-get update
sudo apt-get install curl
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
echo "${blue}Verify that the key ${cyan}9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88${normal}"
echo
sudo apt-key fingerprint 0EBFCD88
echo
sleep 5
sudo add-apt-repository "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
echo
clear
echo
sudo apt-get -y  install docker-ce
echo
clear
echo "${blue}İnstall Complete.${normal}"
echo "${cyan}Waiting."
sleep 1
clear
echo "${blue}İnstall Complete.${normal}"
echo "${cyan}Waiting.."
sleep 1
clear
echo "${blue}İnstall Complete.${normal}"
echo "${cyan}Waiting..."
sleep 1
clear
echo "${blue}İnstall Complete.${normal}"
echo "${cyan}Waiting...."
sleep 1
clear
echo "${blue}İnstall Complete.${normal}"
echo "${cyan}Waiting....."
sleep 1
clear
echo "${blue}İnstall Complete.${normal}"
echo "${cyan}Waiting......"
sleep 1
clear
echo "${blue}İnstall Complete.${normal}"
echo "${cyan}Waiting......."
sleep 1
clear
echo "${blue}İnstall Complete.${normal}"
echo "${cyan}Waiting........"
sleep 1
clear
echo "${blue}İnstall Complete.${normal}"
echo "${cyan}Waiting........."
sleep 1
clear
echo "${blue}İnstall Complete.${normal}"
echo "${cyan}Waiting.........."
clear
echo "${blue}İnstall Complete.${normal}"
sleep 1
sudo systemctl status docker

